#!/bin/bash
set -e

systemctl stop grfics-caldera.service 2>/dev/null || true
systemctl stop grfics-caldera-init.service 2>/dev/null || true

systemctl disable grfics-caldera.service 2>/dev/null || true
systemctl disable grfics-caldera-init.service 2>/dev/null || true
